### PR TITLE
NF improve converter and utils interface that can be handled

### PR DESCRIPTION
**Pull request by htwangtw**
Changes to `converter.py`:
* add default help string when nipype1 provides none
* `inputs_drop` allow converter dropping input specs that is not compatible with pydra
* ensure `name_source` grabbed from nipype1 is a list
* allow using `callable` when encountering nipype1 `genfile` in input spec

Remaining issues for future PRs:
* implement parser for `argstr`: a series of float (`"%f %f"`) and `%g`
* parser for plain text output (possibly a pydra general function; see `AvScale`)
* expand test data type (`ConvertXFM`)
* Some dropped input spec should be implemented as pydra task
    * fwhm to sigma conversion (`Smooth`)
    * number pair to proper input (`ExtractROI`)

To-do:
- [x] fix docstring path issue
- [x] find test data?

### CODE REVIEW

**Comment by djarecka** [comment]
@htwangtw - I was checking the test that is failing - you should probably use `"sep": " ,",` in the `input_spec`, however it won't work with `"argstr": "-f '{filter_columns}'"`. There is one thing to fix in pydra, and I'm planning to work on this tomorrow, but I'm also not completely sure why are you using ` '{filter_columns}'`. Does the command line requires `''` around 1,2,3?

**Comment by htwangtw** [comment]
Thanks for looking into this!

I was writing the test case according to the doc:
```
Usage: 
fsl_regfilt -i <input> -d <design> -f <component numbers or filter threshold> -o <out> [options]

...
Optional arguments (You may optionally specify one or more of):
	-m,--mask	mask image file name
	-f,--filter	filter out part of the regression model, e.g. -f "1,2,3" 
```

It might be fine to remove the `"`?

**Comment by djarecka** [comment]
@effigies - I'm confused about nipype interface `FAST`: [in_files](https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/interfaces/fsl/preprocess.py#L241) use `InputMultiPath` and have no `sep` defined. Shouldn't this mean that the input value is always returned as a list?

The [test](https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/interfaces/fsl/preprocess.py#L383) shows that it returns a single value, but I'm not sure why this is a single value if no `sep` was defined.

**Comment by satra** [comment]
because of this: https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/interfaces/base/core.py#L850

**Comment by djarecka** [comment]
oh, ok, so there is default `sep` value. Do you think we should have in pydra?

**Comment by djarecka** [comment]
@htwangtw - I've fix the bug in pydra: https://github.com/nipype/pydra/pull/466
but I'm still not sure if the command should have "" around `1,2,3`

**Comment by htwangtw** [comment]
I will update my pydra version to the latest and have a look. I will have a look into the original command

**Comment by htwangtw** [comment]
The command itself doesn't require `"` for the input. That was added because that was how this interface was written in nipype. I will add this to my list of "Interface Needing Manual Edit After Conversion"

**Pull request merged**
