### PR TITLE
enable LFS files downloading in github actions

### PR DESCRIPTION
**Pull request by yibeichan**
@djarecka and I found that some of our tests failed because `test.nii.gz` was not fully downloaded due to LFS. So we add this in actions; and hopefully the problem can be solved.

### CODE REVIEW

**Comment by yibeichan** [comment]
@djarecka this change in git actions actually works. I checked the tests; we don't get the following errors anymore
```
E               stderr:
E               Image Exception : #22 :: Failed to read volume /pydra_fsl/pydra/tasks/fsl/tests/data/test
E               Error : Error: short read, file may be truncated
E               terminate called after throwing an instance of 'std::runtime_error'
E                 what():  Failed to read volume /pydra_fsl/pydra/tasks/fsl/tests/data/test
E               Error : Error: short read, file may be truncated
E               /opt/fsl-6.0.4/bin/bet: line 399:   130 Aborted                 (core dumped) ${FSLDIR}/bin/bet2 $IN $OUT $bet2opts
```
everything tested here doesn't include changes from #33. So the tests are failing for other reasons.
At least, I think this pr can fix the Large File Storage problem. We can merge it and then move to another bug...

**Comment by djarecka** [comment]
@yibeichan - perhaps you can merge the master and we will see what is the issue

**Comment by djarecka** [comment]
but not sure why we have complains about `pydra.__version__`: https://github.com/nipype/pydra-fsl/runs/8296934807?check_suite_focus=true

**Comment by yibeichan** [comment]
> but not sure why we have complains about `pydra.__version__`: https://github.com/nipype/pydra-fsl/runs/8296934807?check_suite_focus=true

@djarecka I think the failing is related to https://github.com/nipype/pydra-fsl/blob/6957eb67ea8785f8aae1d2aa858a9a1a85a4b51a/.github/workflows/pythonpackage.yml#L30
because in all other tests (not installing pydra through `git+https://github.com/nipype/pydra.git#egg=pydra`) passed the **Install Pydra** step and successfully printed `pydra.__version__`

**Pull request closed without merging**
