### PR TITLE
CI: Ensure checkout with LFS in fsl_docker job

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #36

### CODE REVIEW

**Comment by effigies** [comment]
Another thing to consider is setting up got archive configuration for setuptools_scm.

**Comment by ghisvail** [comment]
> Another thing to consider is setting up got archive configuration for setuptools_scm.

I suppose you are talking about [this](https://github.com/pypa/setuptools_scm#git-archives), right?

I have no experience with them.

**Comment by ghisvail** [comment]
Looks like the Pydra snapshot is now installed properly.

**Comment by ghisvail** [comment]
Merging #39 and #40 should get us back with a working CI setup, hopefully.

**Comment by ghisvail** [comment]
Apart from issues with the test data files apparently :-/

**Comment by ghisvail** [comment]
> Apart from issues with the test data files apparently :-/

Added Yibei's fix for the missing LFS checkout proposed in #36

**Comment by effigies** [comment]
https://github.com/nipype/pydra/pull/609 should help

**Comment by ghisvail** [comment]
> [nipype/pydra#609](https://github.com/nipype/pydra/pull/609) should help

Means I could just keep Yibei's commit and drop the rest once this is merged, am I correct?

**Comment by effigies** [comment]
That's the idea. Let's see.

**Comment by ghisvail** [comment]
Looks like it's working as expected as far as this PR is concerned.

**Pull request merged**
